const AppPosition = require("../models/app_positions");

const positons = [
  {
    PositionID: 1,
    Positionname: "คนครัว",
    PosID: 10001,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 6,
    Shortname: "พนักงานประกอบอาหาร",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2011-03-10 15:24:35",
  },
  {
    PositionID: 2,
    Positionname: "พนักงานทั่วไป",
    PosID: 10002,
    PPK: 1,
    Nurse: 2,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 131,
    Shortname: "พนักงานทั่วไป",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2011-06-13 10:27:43",
  },
  {
    PositionID: 3,
    Positionname: "คนงานห้องทดลอง",
    PosID: 10003,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 3,
    Shortname: "คนงานห้องทดลอง",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 4,
    Positionname: "คนสวน",
    PosID: 10004,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 0,
    Shortname: "คนสวน",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 5,
    Positionname: "เจ้าพนักงานการเงินและบัญชี",
    PosID: 20412,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 0,
    Shortname: "เจ้าพนักงานการเงินและบัญชี",
    JobDesc: 2,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2011-03-10 15:24:35",
  },
  {
    PositionID: 6,
    Positionname: "เจ้าพนักงานธุรการ",
    PosID: 11612,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 0,
    Shortname: "จพ.ธุรการ",
    JobDesc: 2,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 7,
    Positionname: "เจ้าพนักงานพัสดุ",
    PosID: 11712,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 0,
    Shortname: "จพ.พัสดุ",
    JobDesc: 2,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 8,
    Positionname: "เจ้าพนักงานเภสัชกรรม",
    PosID: 62312,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 2,
    FrameAmount: 1,
    Shortname: "จพ.เภสัชกรรม",
    JobDesc: 1,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 9,
    Positionname: "เจ้าพนักงานวิทยาศาสตร์การแพทย์",
    PosID: 62212,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 2,
    FrameAmount: 1,
    Shortname: "จพ.วิทยาศาสตร์การแพทย์",
    JobDesc: 1,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-08-30 09:22:53",
  },
  {
    PositionID: 10,
    Positionname: "เจ้าพนักงานเวชกรรมฟื้นฟู",
    PosID: 62712,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 2,
    FrameAmount: 0,
    Shortname: "จพ.เวชกรรมฟื้นฟู",
    JobDesc: 1,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 11,
    Positionname: "เจ้าพนักงานโสตทัศนศึกษา",
    PosID: 32512,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 0,
    Shortname: "จพ.โสตทัศนศึกษา",
    JobDesc: 2,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 12,
    Positionname: "เจ้าหน้าที่ธุรการ",
    PosID: 11601,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 4,
    Shortname: "จ.ธุรการ",
    JobDesc: 2,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 125,
    Positionname: "เจ้าหน้าที่เวชสถิติ",
    PosID: 60326,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "จ.เวชสถิติ",
    JobDesc: null,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-08-30 09:22:53",
  },
  {
    PositionID: 15,
    Positionname: "นักจัดการงานทั่วไป",
    PosID: 11103,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 0,
    Shortname: "นักจัดการงานทั่วไป",
    JobDesc: 2,
    Educate: "up",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 16,
    Positionname: "นักวิชาการพัสดุ",
    PosID: 11730,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 0,
    Shortname: "นักวิชาการพัสดุ",
    JobDesc: 2,
    Educate: "up",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 17,
    Positionname: "เจ้าหน้าที่บันทึกข้อมูล",
    PosID: 11801,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 4,
    Shortname: "จ.บันทึกข้อมูล",
    JobDesc: 2,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 18,
    Positionname: "เจ้าหน้าที่ประชาสัมพันธ์",
    PosID: 31801,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 1,
    Shortname: "จ.ประชาสัมพันธ์",
    JobDesc: 2,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-08-30 09:22:53",
  },
  {
    PositionID: 19,
    Positionname: "เจ้าหน้าที่พยาบาล",
    PosID: 61601,
    PPK: 1,
    Nurse: 2,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 1,
    FrameAmount: 0,
    Shortname: "จ.พยาบาล",
    JobDesc: 1,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 20,
    Positionname: "เจ้าหน้าที่พัสดุ",
    PosID: 11701,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 2,
    Shortname: "จ.พัสดุ",
    JobDesc: 2,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 21,
    Positionname: "เจ้าหน้าที่พิมพ์ดีด",
    PosID: 11901,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 9,
    Shortname: "จ.พิมพ์ดีด",
    JobDesc: null,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 22,
    Positionname: "เจ้าพนักงานรังสีการแพทย์",
    PosID: 61712,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 2,
    FrameAmount: 0,
    Shortname: "จพ.รังสีการแพทย์",
    JobDesc: 1,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-06-14 14:19:52",
  },
  {
    PositionID: 23,
    Positionname: "เจ้าพนักงานเวชสถิติ",
    PosID: 12305,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 0,
    Shortname: "จพ.เวชสถิติ",
    JobDesc: 2,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-06-14 14:19:52",
  },
  {
    PositionID: 24,
    Positionname: "เจ้าหน้าที่โสตทัศนศึกษา",
    PosID: 32501,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 0,
    Shortname: "จ.โสตทัศนศึกษา",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 25,
    Positionname: "เจ้าพนักงานอาชีวบำบัด",
    PosID: 61902,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 2,
    FrameAmount: 0,
    Shortname: "จพ.อาชีวบำบัด",
    JobDesc: 1,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-06-14 14:18:54",
  },
  {
    PositionID: 26,
    Positionname: "ช่างกายอุปกรณ์",
    PosID: 75601,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 2,
    FrameAmount: 0,
    Shortname: "ช่างกายอุปกรณ์",
    JobDesc: 1,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 27,
    Positionname: "ช่างเชื่อม",
    PosID: 10005,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 0,
    Shortname: "ช่างเชื่อม",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 28,
    Positionname: "ช่างท่อ",
    PosID: 10006,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 3,
    Shortname: "ช่างท่อ",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 29,
    Positionname: "ช่างทันตกรรม",
    PosID: 75702,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 2,
    FrameAmount: 0,
    Shortname: "ช่างทันตกรรม",
    JobDesc: null,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 30,
    Positionname: "ช่างเทคนิค",
    PosID: 73501,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 0,
    Shortname: "ช่างเทคนิค",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 31,
    Positionname: "ช่างปูน",
    PosID: 10007,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 2,
    Shortname: "ช่างปูน",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 32,
    Positionname: "ช่างไฟฟ้า",
    PosID: 73001,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 1,
    Shortname: "ช่างไฟฟ้า",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 33,
    Positionname: "ช่างภาพการแพทย์",
    PosID: 75003,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 0,
    Shortname: "ช่างภาพการแพทย์",
    JobDesc: 3,
    Educate: "up",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 34,
    Positionname: "ช่างไม้",
    PosID: 10008,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 5,
    Shortname: "ช่างไม้",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 35,
    Positionname: "ช่างอิเลคโทรนิกส์",
    PosID: 10009,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 0,
    Shortname: "ช่างอิเลคโทรนิกส์",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 36,
    Positionname: "ช่างอุปกรณ์การแพทย์",
    PosID: 10010,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 4,
    FrameAmount: 0,
    Shortname: "ช่างอุปกรณ์การแพทย์",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 37,
    Positionname: "ทันตแพทย์",
    PosID: 60204,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 1,
    FrameAmount: 0,
    Shortname: "ทันตแพทย์",
    JobDesc: 1,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 38,
    Positionname: "นักกายภาพบำบัด",
    PosID: 61803,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 2,
    FrameAmount: 1,
    Shortname: "นักกายภาพบำบัด",
    JobDesc: 1,
    Educate: "up",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 39,
    Positionname: "พนักงานสถานที่",
    PosID: 10011,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 4,
    FrameAmount: 0,
    Shortname: "พนักงานสถานที่",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2011-03-16 14:46:45",
  },
  {
    PositionID: 40,
    Positionname: "นักจิตวิทยา",
    PosID: 61203,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 2,
    FrameAmount: 0,
    Shortname: "นักจิตวิทยา",
    JobDesc: 1,
    Educate: "up",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 41,
    Positionname: "นักเทคนิคการแพทย์",
    PosID: 60404,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 2,
    FrameAmount: 0,
    Shortname: "นักเทคนิคการแพทย์",
    JobDesc: 1,
    Educate: "up",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 42,
    Positionname: "นักประชาสัมพันธ์",
    PosID: 31813,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 1,
    Shortname: "นักประชาสัมพันธ์",
    JobDesc: 2,
    Educate: "up",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 43,
    Positionname: "นักโภชนาการ",
    PosID: 60813,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 4,
    Shortname: "นักโภชนาการ",
    JobDesc: 3,
    Educate: "up",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 44,
    Positionname: "นักรังสีการแพทย์",
    PosID: 61723,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 2,
    FrameAmount: 0,
    Shortname: "นักรังสีการแพทย์",
    JobDesc: 1,
    Educate: "up",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 45,
    Positionname: "นักวิชาการควบคุมโรค",
    PosID: 63123,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 2,
    FrameAmount: 0,
    Shortname: "นวก.ควบคุมโรค",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 46,
    Positionname: "นักวิชาการเงินและบัญชี",
    PosID: 20423,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 0,
    Shortname: "นวก.การเงินและบัญชี",
    JobDesc: 2,
    Educate: "up",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 47,
    Positionname: "นักวิชาการประกันภัย",
    PosID: 22803,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 4,
    FrameAmount: 0,
    Shortname: "นวก.ประกันภัย",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 48,
    Positionname: "นักวิชาการศึกษา",
    PosID: 80103,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 4,
    FrameAmount: 0,
    Shortname: "นวก.ศึกษา",
    JobDesc: null,
    Educate: "up",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 49,
    Positionname: "นักวิชาการส่งเสริมสุขภาพ",
    PosID: 63023,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 2,
    FrameAmount: 0,
    Shortname: "นวก.ส่งเสริมสุขภาพ",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 50,
    Positionname: "นักวิชาการสาธารณสุข",
    PosID: 62503,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 2,
    FrameAmount: 0,
    Shortname: "นวก.สาธารณสุข",
    JobDesc: 3,
    Educate: "up",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 51,
    Positionname: "นักวิชาการสุขศึกษา",
    PosID: 61303,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 2,
    FrameAmount: 0,
    Shortname: "นวก.สุขศึกษา",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 52,
    Positionname: "นักวิชาการสุขาภิบาล",
    PosID: 61403,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 2,
    FrameAmount: 0,
    Shortname: "นวก.สุขาภิบาล",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 53,
    Positionname: "นักวิชาการโสตทัศนศึกษา",
    PosID: 32523,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 0,
    Shortname: "นวก.โสตทัศนศึกษา",
    JobDesc: 2,
    Educate: "up",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 54,
    Positionname: "นักวิทยาศาสตร์การแพทย์",
    PosID: 60403,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 2,
    FrameAmount: 0,
    Shortname: "นักวิทยาศาสตร์การแพทย์",
    JobDesc: 1,
    Educate: "up",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-08-30 09:22:53",
  },
  {
    PositionID: 55,
    Positionname: "นักวิชาการสถิติ",
    PosID: 12223,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 0,
    Shortname: "นวก.สถิติ",
    JobDesc: 2,
    Educate: "up",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 56,
    Positionname: "นักสังคมสงเคราะห์",
    PosID: 82903,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 2,
    FrameAmount: 0,
    Shortname: "นักสังคมสงเคราะห์",
    JobDesc: 2,
    Educate: "up",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 57,
    Positionname: "นักกิจกรรมบำบัด",
    PosID: 61913,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 2,
    FrameAmount: 1,
    Shortname: "นักกิจกรรมบำบัด",
    JobDesc: 1,
    Educate: "up",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-05-25 11:10:12",
  },
  {
    PositionID: 58,
    Positionname: "นายช่างเทคนิค",
    PosID: 73512,
    PPK: 1,
    Nurse: 2,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 0,
    Shortname: "นายช่างเทคนิค",
    JobDesc: 2,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 59,
    Positionname: "นายแพทย์",
    PosID: 60104,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 1,
    FrameAmount: 2,
    Shortname: "นายแพทย์",
    JobDesc: 1,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 60,
    Positionname: "บรรณารักษ์",
    PosID: 81303,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 0,
    Shortname: "บรรณารักษ์",
    JobDesc: 2,
    Educate: "up",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 61,
    Positionname: "นักทรัพยากรบุคคล",
    PosID: 11403,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 0,
    Shortname: "นักทรัพยากรบุคคล",
    JobDesc: 2,
    Educate: "up",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 62,
    Positionname: "เจ้าพนักงานทันตสาธารณสุข",
    PosID: 62601,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 2,
    FrameAmount: 0,
    Shortname: "จพ.ทันตสาธารณสุข",
    JobDesc: 1,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-06-14 14:20:02",
  },
  {
    PositionID: 63,
    Positionname: "พนักงานช่วยเหลือคนไข้",
    PosID: 10012,
    PPK: 1,
    Nurse: 2,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 197,
    Shortname: "พนักงานช่วยเหลือคนไข้",
    JobDesc: 1,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2011-06-13 10:30:24",
  },
  {
    PositionID: 64,
    Positionname: "ผู้ช่วยเภสัชกร",
    PosID: 10013,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 4,
    FrameAmount: 20,
    Shortname: "ผู้ช่วยเภสัชกร",
    JobDesc: 1,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 65,
    Positionname: "ผู้อำนวยการโรงพยาบาล",
    PosID: 10014,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 1,
    FrameAmount: 0,
    Shortname: "ผู้อำนวยการโรงพยาบาล",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 66,
    Positionname: "พนักงานขับรถยนต์",
    PosID: 10015,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 3,
    Shortname: "พนักงานขับรถยนต์",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-08-26 10:28:55",
  },
  {
    PositionID: 67,
    Positionname: "พนักงานซักฟอก",
    PosID: 10016,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 0,
    Shortname: "พนักงานซักฟอก",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-08-30 09:22:53",
  },
  {
    PositionID: 68,
    Positionname: "พนักงานซักรีด",
    PosID: 10017,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 6,
    Shortname: "พนักงานซักรีด",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-09-01 11:08:05",
  },
  {
    PositionID: 69,
    Positionname: "พนักงานตัดเย็บเสื้อผ้า",
    PosID: 10018,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 0,
    Shortname: "พนักงานตัดเย็บเสื้อผ้า",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-09-01 11:08:05",
  },
  {
    PositionID: 70,
    Positionname: "พนักงานโทรศัพท์",
    PosID: 10019,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 1,
    Shortname: "พนักงานรับโทรศัพท์",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2011-03-10 15:24:35",
  },
  {
    PositionID: 71,
    Positionname: "พนักงานบัตรรายงานโรค",
    PosID: 10020,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 11,
    Shortname: "พนักงานบัตรรายงานโรค",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2011-03-10 15:30:12",
  },
  {
    PositionID: 72,
    Positionname: "พนักงานประจำตึก",
    PosID: 10021,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 0,
    Shortname: "พ.ประจำตึก",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 73,
    Positionname: "พนักงานเปล",
    PosID: 10022,
    PPK: 1,
    Nurse: 2,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 24,
    Shortname: "พนักงานเปล",
    JobDesc: 1,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-08-26 10:45:11",
  },
  {
    PositionID: 74,
    Positionname: "พนักงานพิมพ์",
    PosID: 10023,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 0,
    Shortname: "พนักงานพิมพ์",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-09-01 11:08:05",
  },
  {
    PositionID: 76,
    Positionname: "พนักงานเภสัชกรรม",
    PosID: 10025,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 0,
    Shortname: "พนักงานเภสัชกรรม",
    JobDesc: 1,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-08-26 15:37:03",
  },
  {
    PositionID: 77,
    Positionname: "พนักงานรหัส",
    PosID: 10026,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 0,
    Shortname: "พ.รหัส",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 78,
    Positionname: "พนักงานผ่าและรักษาศพ",
    PosID: 10027,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 0,
    Shortname: "พนักงานผ่าและรักษาศพ",
    JobDesc: 1,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2011-05-04 09:51:46",
  },
  {
    PositionID: 79,
    Positionname: "พนักงานห้องทดลอง",
    PosID: 10028,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 7,
    Shortname: "พนักงานห้องทดลอง",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-09-01 11:08:05",
  },
  {
    PositionID: 80,
    Positionname: "พยาบาลเทคนิค",
    PosID: 61502,
    PPK: 1,
    Nurse: 2,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 1,
    FrameAmount: 0,
    Shortname: "พยาบาลเทคนิค",
    JobDesc: 1,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 81,
    Positionname: "พยาบาลวิชาชีพ",
    PosID: 61523,
    PPK: 1,
    Nurse: 2,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 1,
    FrameAmount: 13,
    Shortname: "พยาบาลวิชาชีพ",
    JobDesc: 1,
    Educate: "up",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 82,
    Positionname: "เภสัชกร",
    PosID: 60603,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 1,
    FrameAmount: 0,
    Shortname: "เภสัชกร",
    JobDesc: 1,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 83,
    Positionname: "โภชนากร",
    PosID: 60802,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 0,
    Shortname: "โภชนากร",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 84,
    Positionname: "พนักงานรักษาความปลอดภัย",
    PosID: 10029,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 16,
    Shortname: "พนักงานรักษาความปลอดภัย",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-08-26 10:28:55",
  },
  {
    PositionID: 85,
    Positionname: "รองผู้อำนวยการฝ่ายการแพทย์",
    PosID: 10030,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 1,
    FrameAmount: 0,
    Shortname: "รอง ผอ.ฝ่ายการแพทย์",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 86,
    Positionname: "รองผู้อำนวยการฝ่ายการพยาบาล",
    PosID: 10031,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 1,
    FrameAmount: 1,
    Shortname: "รอง ผอ.ฝ่ายการพยาบาล",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 87,
    Positionname: "รองผู้อำนวยการฝ่ายบริหาร",
    PosID: 10032,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 1,
    Shortname: "รอง ผอ.ฝ่ายบริหาร",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 88,
    Positionname: "พนักงานประกอบอาหาร",
    PosID: 10033,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 1,
    Shortname: "พนักงานประกอบอาหาร",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2016-08-10 10:03:54",
  },
  {
    PositionID: 89,
    Positionname: "ผู้ดูแลหมวดสถานที่ (หัวหน้า)",
    PosID: 10034,
    PPK: 1,
    Nurse: 1,
    Comment: "",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 0,
    Shortname: "ผู้ดูแลหมวดสถานที่ (หัวหน้า)",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-08-26 14:19:43",
  },
  {
    PositionID: 90,
    Positionname: "พนักงานกู้ชีพ",
    PosID: 10050,
    PPK: 1,
    Nurse: 2,
    Comment: null,
    Officegroup: 1,
    BusinessGroup: 2,
    FrameAmount: 0,
    Shortname: "พนักงานกู้ชีพ",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2021-02-04 16:20:46",
  },
  {
    PositionID: 91,
    Positionname: "พนักงานห้องบัตร",
    PosID: 60302,
    PPK: 1,
    Nurse: 1,
    Comment: "กำหนดเอง",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 0,
    Shortname: "พนักงานห้องบัตร",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2011-03-10 15:30:12",
  },
  {
    PositionID: 92,
    Positionname: "นักวิชาการคอมพิวเตอร์",
    PosID: 60303,
    PPK: 1,
    Nurse: 1,
    Comment: "กำหนดเอง",
    Officegroup: 1,
    BusinessGroup: 4,
    FrameAmount: 0,
    Shortname: "นวก.คอมพิวเตอร์",
    JobDesc: null,
    Educate: "up",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 93,
    Positionname: "ยังไม่ระบุตำแหน่ง",
    PosID: 0,
    PPK: 1,
    Nurse: 1,
    Comment: "กำหนดเอง",
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "ยังไม่ระบุตำแหน่ง",
    JobDesc: null,
    Educate: null,
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 94,
    Positionname: "พนักงานนำส่งผู้ป่วย",
    PosID: 60304,
    PPK: 1,
    Nurse: 1,
    Comment: "กำหนดเอง",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 0,
    Shortname: "พ.นำส่งผู้ป่วย",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 95,
    Positionname: "เจ้าพนักงานสาธารณสุข",
    PosID: 63502,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: 1,
    BusinessGroup: 2,
    FrameAmount: 4,
    Shortname: "จพ.สาธารณสุข",
    JobDesc: 3,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-08-30 09:22:53",
  },
  {
    PositionID: 96,
    Positionname: "พนักงานจัดเก็บรายได้",
    PosID: 60305,
    PPK: 1,
    Nurse: 2,
    Comment: "กำหนดเอง",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 0,
    Shortname: "พ.จัดเก็บรายได้",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 98,
    Positionname: "เจ้าหน้าที่การเงินและบัญชี",
    PosID: 60307,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 0,
    Shortname: "จ.การเงินและบัญชี",
    JobDesc: 2,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 99,
    Positionname: "เจ้าหน้าที่ห้องสมุด",
    PosID: 60308,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: 1,
    BusinessGroup: 3,
    FrameAmount: 0,
    Shortname: "จ.ห้องสมุด",
    JobDesc: null,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 100,
    Positionname: "ผู้ช่วยเจ้าหน้าที่อนามัย",
    PosID: 60309,
    PPK: 1,
    Nurse: 1,
    Comment: "กำหนดเอง",
    Officegroup: 3,
    BusinessGroup: 4,
    FrameAmount: 0,
    Shortname: "ผู้ช่วย จ.อนามัย",
    JobDesc: 1,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 101,
    Positionname: "ลูกมือช่าง",
    PosID: 60310,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "ผู้ช่วยช่างทั่วไป",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2011-03-10 15:33:31",
  },
  {
    PositionID: 102,
    Positionname: "พนักงานกายภาพบำบัด",
    PosID: 60311,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "พนักงานกายภาพบำบัด",
    JobDesc: 1,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2011-03-10 15:30:12",
  },
  {
    PositionID: 103,
    Positionname: "พนักงานประจำห้องทดลอง",
    PosID: 60312,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "พนักงานประจำห้องทดลอง",
    JobDesc: 1,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2011-03-10 15:30:12",
  },
  {
    PositionID: 104,
    Positionname: "พนักงานบริการอัดสำเนา",
    PosID: 60313,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "พ.บริการอัดสำเนา",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 105,
    Positionname: "ผู้ช่วยนักกายภาพบำบัด",
    PosID: 60314,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "ผช.นักกายภาพ",
    JobDesc: 1,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 106,
    Positionname: "พนักงานห้องผ่าตัด",
    PosID: 60315,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "พนักงานห้องผ่าตัด",
    JobDesc: 1,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-08-26 15:37:03",
  },
  {
    PositionID: 107,
    Positionname: "พนักงานห้องเฝือก",
    PosID: 60316,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "พนักงานห้องเฝือก",
    JobDesc: 1,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2011-03-10 15:30:12",
  },
  {
    PositionID: 108,
    Positionname: "พนักงานห้องยา",
    PosID: 60317,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "พนักงานประจำห้องยา",
    JobDesc: 1,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2011-03-10 15:30:12",
  },
  {
    PositionID: 109,
    Positionname: "แม่บ้าน",
    PosID: 60318,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 3,
    Shortname: "แม่บ้าน",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 110,
    Positionname: "พนักงานขับรถยนต์ (หัวหน้า)",
    PosID: 60319,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 1,
    Shortname: "พนักงานขับรถยนต์ (หัวหน้า)",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-08-26 14:19:43",
  },
  {
    PositionID: 111,
    Positionname: "เสมียนพนักงาน",
    PosID: 60320,
    PPK: 1,
    Nurse: 1,
    Comment: "กำหนดเอง",
    Officegroup: 3,
    BusinessGroup: null,
    FrameAmount: 1,
    Shortname: "เสมียนพนักงาน",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 112,
    Positionname: "เจ้าหน้าที่ประจำศูนย์ช่วยเหลือคนพิการ",
    PosID: 60321,
    PPK: 1,
    Nurse: 1,
    Comment: "กำหนดเอง",
    Officegroup: 3,
    BusinessGroup: null,
    FrameAmount: 1,
    Shortname: "จ.ประจำศูนย์ช่วยเหลือคนพิการ",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-08-30 09:22:53",
  },
  {
    PositionID: 114,
    Positionname: "เจ้าหน้าที่เครื่องคอมพิวเตอร์",
    PosID: 60323,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "จ.เครื่องคอมพิวเตอร์",
    JobDesc: 2,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-08-30 09:22:53",
  },
  {
    PositionID: 115,
    Positionname: "เจ้าหน้าที่โครงการศูนย์รับบริจาคอวัยวะ",
    PosID: 60324,
    PPK: 1,
    Nurse: 1,
    Comment: "กำหนดเอง",
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 1,
    Shortname: "จ.โครงการศูนย์รับบริจาคอวัยวะ",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-08-30 09:22:53",
  },
  {
    PositionID: 116,
    Positionname: "นายช่างอิเลคโทรนิกส์",
    PosID: 10051,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "ช่างอิเลคโทรนิกส์",
    JobDesc: 2,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 123,
    Positionname: "แพทย์แผนไทย",
    PosID: 60501,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "แพทย์แผนไทย",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 124,
    Positionname: "เสมียนหอ",
    PosID: 60325,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "เสมียนหอ",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 127,
    Positionname: "เจ้าพนักงานเผยแพร่ประชาสัมพันธ์",
    PosID: 31802,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "จพ.เผยแพร่ประชาสัมพันธ์",
    JobDesc: null,
    Educate: "down",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-08-30 09:22:53",
  },
  {
    PositionID: 128,
    Positionname: "พนักงานห้องปฏิบัติการ",
    PosID: 82904,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "พนักงานห้องปฏิบัติการ",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-08-26 15:37:03",
  },
  {
    PositionID: 129,
    Positionname: "พนักงานธุรการ",
    PosID: 82905,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "พนักงานธุรการ",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-08-26 10:28:55",
  },
  {
    PositionID: 130,
    Positionname: "พนักงานซ่อมเอกสาร",
    PosID: 82906,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "พนักงานซ่อมเอกสาร",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-08-30 09:22:53",
  },
  {
    PositionID: 131,
    Positionname: "พนักงานเก็บเอกสาร",
    PosID: 82907,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "พนักงานเก็บเอกสาร",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-08-30 09:22:53",
  },
  {
    PositionID: 132,
    Positionname: "พนักงานบริการ",
    PosID: 82908,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "พนักงานบริการ",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2011-03-10 15:30:12",
  },
  {
    PositionID: 133,
    Positionname: "พนักงานจัดการหอพัก",
    PosID: 82909,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "พนักงานจัดการหอพัก",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-08-27 08:54:57",
  },
  {
    PositionID: 134,
    Positionname: "ครูพี่เลี้ยง",
    PosID: 82910,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "ครูพี่เลี้ยง",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2010-08-26 10:45:11",
  },
  {
    PositionID: 136,
    Positionname: "เจ้าหน้าที่บริหารงานทั่วไป",
    PosID: 82911,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "จ.บริหารงานทั่วไป",
    JobDesc: null,
    Educate: "up",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 137,
    Positionname: "นักวิชาการแพทย์แผนไทย",
    PosID: 82912,
    PPK: 1,
    Nurse: 1,
    Comment: "กำหนดเอง",
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "นวก.แพทย์แผนไทย",
    JobDesc: 1,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 138,
    Positionname: "ผู้ช่วยทันตแพทย์",
    PosID: 82914,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "ผู้ช่วยทันตแพทย์",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: null,
  },
  {
    PositionID: 140,
    Positionname: "นักวิเคราะห์นโยบายและแผน",
    PosID: 10704,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "นักวิเคราะห์นโยบายและแผน",
    JobDesc: null,
    Educate: "up",
    UserKey: 1976,
    KeyDate: "2009-10-28",
    UptoDate: null,
  },
  {
    PositionID: 141,
    Positionname: "นักเทคโนโลยีหัวใจและทรวงอก",
    PosID: 82913,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "นักเทคโนโลยีหัวใจและทรวงอก",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2009-11-23 14:29:35",
  },
  {
    PositionID: 142,
    Positionname: "ผู้ช่วยเจ้าหน้าที่สาธารณสุข",
    PosID: 82915,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "ผู้ช่วยเจ้าหน้าที่สาธารณสุข",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2009-11-23 14:29:35",
  },
  {
    PositionID: 143,
    Positionname: "ช่างโยธา",
    PosID: 71401,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 1,
    Shortname: "ช่างโยธา",
    JobDesc: null,
    Educate: "down",
    UserKey: 1871,
    KeyDate: "2009-12-09",
    UptoDate: null,
  },
  {
    PositionID: 149,
    Positionname: "ช่างต่อท่อ",
    PosID: 10059,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 5,
    Shortname: "ช่างต่อท่อ",
    JobDesc: null,
    Educate: "down",
    UserKey: 5,
    KeyDate: "2010-08-25",
    UptoDate: "2010-11-09 09:34:59",
  },
  {
    PositionID: 152,
    Positionname: "พนักงานรับโทรศัพท์",
    PosID: 82917,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "พนักงานรับโทรศัพท์",
    JobDesc: null,
    Educate: "down",
    UserKey: 5,
    KeyDate: "2010-09-07",
    UptoDate: "2011-03-10 15:30:12",
  },
  {
    PositionID: 154,
    Positionname: "ผู้ช่วยช่างทั่วไป",
    PosID: 82919,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "ผู้ช่วยช่างทั่วไป",
    JobDesc: null,
    Educate: "down",
    UserKey: 5,
    KeyDate: "2010-09-07",
    UptoDate: null,
  },
  {
    PositionID: 155,
    Positionname: "พนักงานประจำห้องยา",
    PosID: 82920,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 20,
    Shortname: "พนักงานประจำห้องยา",
    JobDesc: null,
    Educate: "down",
    UserKey: 5,
    KeyDate: "2010-10-02",
    UptoDate: null,
  },
  {
    PositionID: 156,
    Positionname: "ช่างตัดเย็บผ้า",
    PosID: 82921,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 3,
    Shortname: "ช่างตัดเย็บผ้า",
    JobDesc: null,
    Educate: "down",
    UserKey: 5,
    KeyDate: "2010-10-02",
    UptoDate: null,
  },
  {
    PositionID: 157,
    Positionname: "เจ้าพนักงานเครื่องคอมพิวเตอร์",
    PosID: 72902,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "จพ.เครื่องคอมพิวเตอร์",
    JobDesc: null,
    Educate: "down",
    UserKey: 1871,
    KeyDate: "2011-05-06",
    UptoDate: null,
  },
  {
    PositionID: 158,
    Positionname: "พนักงานการเงินและบัญชี",
    PosID: 16052,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "พ.การเงินและบัญชี",
    JobDesc: null,
    Educate: "down",
    UserKey: 1871,
    KeyDate: "2011-06-14",
    UptoDate: null,
  },
  {
    PositionID: 159,
    Positionname: "ผู้ช่วยพยาบาล",
    PosID: 16086,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "ผู้ช่วยพยาบาล",
    JobDesc: null,
    Educate: "down",
    UserKey: 1871,
    KeyDate: "2011-06-15",
    UptoDate: null,
  },
  {
    PositionID: 160,
    Positionname: "พนักงานพัสดุ",
    PosID: 16051,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "พนักงานพัสดุ",
    JobDesc: null,
    Educate: "down",
    UserKey: 1871,
    KeyDate: "2011-07-11",
    UptoDate: null,
  },
  {
    PositionID: 161,
    Positionname: "พนักงานเก็บเงิน",
    PosID: 1504,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "พนักงานเก็บเงิน",
    JobDesc: null,
    Educate: "down",
    UserKey: 1871,
    KeyDate: "2011-09-01",
    UptoDate: null,
  },
  {
    PositionID: 162,
    Positionname: "พนักงานการแพทย์และรังสีเทคนิค",
    PosID: 2413,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "พนักงานการแพทย์และรังสีเทคนิค",
    JobDesc: null,
    Educate: "down",
    UserKey: 1871,
    KeyDate: "2011-09-01",
    UptoDate: null,
  },
  {
    PositionID: 163,
    Positionname: "นักการแพทย์แผนไทย",
    PosID: 82922,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 3,
    Shortname: "นักการแพทย์แผนไทย",
    JobDesc: null,
    Educate: "up",
    UserKey: 5,
    KeyDate: "2011-09-07",
    UptoDate: null,
  },
  {
    PositionID: 164,
    Positionname: "พนักงานช่วยการพยาบาล",
    PosID: 2401,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "พนักงานช่วยการพยาบาล",
    JobDesc: null,
    Educate: "down",
    UserKey: 1871,
    KeyDate: "2011-09-08",
    UptoDate: null,
  },
  {
    PositionID: 165,
    Positionname: "ช่างซ่อมเครื่องทำความเย็น",
    PosID: 39063,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "ช่างซ่อมเครื่องทำความเย็น",
    JobDesc: null,
    Educate: "down",
    UserKey: 1871,
    KeyDate: "2011-12-02",
    UptoDate: null,
  },
  {
    PositionID: 167,
    Positionname: "แพทย์แผนจีน",
    PosID: 82923,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "แพทย์แผนจีน",
    JobDesc: null,
    Educate: "none",
    UserKey: null,
    KeyDate: null,
    UptoDate: "2018-01-30 10:07:41",
  },
  {
    PositionID: 168,
    Positionname: "พนักงานบริการเอกสารทั่วไป",
    PosID: 1409,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "พนักงานบริการเอกสารทั่วไป",
    JobDesc: null,
    Educate: "down",
    UserKey: 1871,
    KeyDate: "2012-12-12",
    UptoDate: null,
  },
  {
    PositionID: 169,
    Positionname: "ช่างไฟฟ้าและอิเลคทรอนิคส์",
    PosID: 3203,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "ช่างไฟฟ้าและอิเลคทรอนิคส์",
    JobDesc: null,
    Educate: "down",
    UserKey: 1871,
    KeyDate: "2013-03-08",
    UptoDate: null,
  },
  {
    PositionID: 170,
    Positionname: "นักจิตวิทยาคลินิก",
    PosID: 61204,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "นักจิตวิทยาคลินิก",
    JobDesc: null,
    Educate: "up",
    UserKey: 1871,
    KeyDate: "2013-03-08",
    UptoDate: null,
  },
  {
    PositionID: 171,
    Positionname: "พนักงานโสตทัศนศึกษา",
    PosID: 1505,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 1,
    Shortname: "พนักงานโสตทัศนศึกษา",
    JobDesc: null,
    Educate: "down",
    UserKey: 1871,
    KeyDate: "2014-01-20",
    UptoDate: null,
  },
  {
    PositionID: 174,
    Positionname: "พนักงานวิทยาศาสตร์",
    PosID: 2513,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 15,
    Shortname: "พนักงานวิทยาศาสตร์",
    JobDesc: null,
    Educate: "down",
    UserKey: 1871,
    KeyDate: "2014-01-27",
    UptoDate: null,
  },
  {
    PositionID: 175,
    Positionname: "พนักงานห้องสมุด",
    PosID: 2210,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 2,
    Shortname: "พนักงานห้องสมุด",
    JobDesc: null,
    Educate: "down",
    UserKey: 1871,
    KeyDate: "2014-01-28",
    UptoDate: null,
  },
  {
    PositionID: 177,
    Positionname: "พนักงานเกษตรพื้นฐาน",
    PosID: 1201,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 10,
    Shortname: "พนักงานเกษตรพื้นฐาน",
    JobDesc: null,
    Educate: "down",
    UserKey: 1871,
    KeyDate: "2014-06-23",
    UptoDate: null,
  },
  {
    PositionID: 178,
    Positionname: "ช่างซ่อมบำรุง",
    PosID: 3333,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "ช่างซ่อมบำรุง",
    JobDesc: null,
    Educate: "down",
    UserKey: 1871,
    KeyDate: "2014-08-22",
    UptoDate: null,
  },
  {
    PositionID: 179,
    Positionname: "หัวหน้าพยาบาล (พยาบาลวิชาชีพด้านการพยาบาล)",
    PosID: 61525,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 1,
    Shortname: "หัวหน้าพยาบาล (พยาบาลวิชาชีพด้านการพยาบาล)",
    JobDesc: null,
    Educate: "up",
    UserKey: 1871,
    KeyDate: "2014-10-20",
    UptoDate: null,
  },
  {
    PositionID: 180,
    Positionname: "ช่างฝีมือทั่วไป",
    PosID: 3335,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 5,
    Shortname: "ช่างฝีมือทั่วไป",
    JobDesc: null,
    Educate: "down",
    UserKey: 1871,
    KeyDate: "2014-10-28",
    UptoDate: null,
  },
  {
    PositionID: 181,
    Positionname: "เจ้าพนักงานสถิติ",
    PosID: 41005,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 1,
    Shortname: "จพ.สถิติ",
    JobDesc: null,
    Educate: "down",
    UserKey: 1871,
    KeyDate: "2015-03-05",
    UptoDate: null,
  },
  {
    PositionID: 182,
    Positionname: "นิติกร",
    PosID: 44,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "นิติกร",
    JobDesc: null,
    Educate: "up",
    UserKey: 1871,
    KeyDate: "2015-06-25",
    UptoDate: null,
  },
  {
    PositionID: 183,
    Positionname: "นักปฏิบัติการฉุกเฉินการแพทย์",
    PosID: 19250,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "น.ปฏิบัติการฉุกเฉินการแพทย์",
    JobDesc: null,
    Educate: "up",
    UserKey: 496,
    KeyDate: "2018-01-30",
    UptoDate: null,
  },
  {
    PositionID: 184,
    Positionname: "นักเวชศาสตร์การสื่อความหมาย",
    PosID: 10095,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 0,
    Shortname: "น.เวชศาสตร์การสื่อความหมาย",
    JobDesc: null,
    Educate: "up",
    UserKey: 1971,
    KeyDate: null,
    UptoDate: "2019-01-15 13:59:11",
  },
  {
    PositionID: 185,
    Positionname: "นักฟิสิกส์การแพทย์",
    PosID: 36021,
    PPK: 1,
    Nurse: 1,
    Comment: null,
    Officegroup: null,
    BusinessGroup: null,
    FrameAmount: 2,
    Shortname: "นักฟิสิกส์การแพทย์",
    JobDesc: null,
    Educate: "up",
    UserKey: 1976,
    KeyDate: "2020-11-02",
    UptoDate: null,
  },
];

async function seed() {
  await AppPosition.bulkCreate(positons);
  console.log("App positon seeder sucess");
}

seed();
