const AppGroup = require("../models/app_group");

groups = [
  {
    id: 1,
    groupname: "ห้องบัตร",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 2,
    groupname: "ward",
    active: "Y",
    edituserid: 5,
    userlogid: 5,
  },
  {
    id: 3,
    groupname: "drug_purchase",
    active: "Y",
    edituserid: 5,
    userlogid: 5,
  },
  {
    id: 4,
    groupname: "itcenter",
    active: "Y",
    edituserid: 5,
    userlogid: 5,
  },
  {
    id: 5,
    groupname: "แพทย์อายุรกรรม",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 6,
    groupname: "แพทย์ศัลยกรรมกระดูก",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 7,
    groupname: "จัดเก็บผู้ป่วยใน",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 8,
    groupname: "แพทย์กุมารเวชกรรม",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 9,
    groupname: "แพทย์สูติ-นรีเวชกรรม",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 10,
    groupname: "แพทย์จิตเวช",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 11,
    groupname: "แพทย์จักษุ",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 12,
    groupname: "แพทย์โสต ศอ นาสิก",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 13,
    groupname: "แพทย์เวชกรรมฟื้นฟู",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 14,
    groupname: "จนท.ทันตกรรม",
    active: "Y",
    edituserid: 936,
    userlogid: 936,
  },
  {
    id: 15,
    groupname: "ห้องยา",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 16,
    groupname: "วิสัญญี",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 17,
    groupname: "OR",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 18,
    groupname: "แพทย์เวชกรรมสังคม",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 19,
    groupname: "แพทย์เวชศาสตร์ครอบครัว",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 20,
    groupname: "Patho",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 21,
    groupname: "OPD",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 22,
    groupname: "โภชนศาสตร์",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 23,
    groupname: "ประชาสัมพันธ์",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 24,
    groupname: "Lab",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 25,
    groupname: "แพทย์ศัลยกรรม",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 26,
    groupname: "แพทย์วิสัญญี",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 27,
    groupname: "แพทย์รังสีวิทยา",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 28,
    groupname: "แพทย์นิติเวชวิทยา",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 29,
    groupname: "ทันตแพทย์",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 30,
    groupname: "แพทย์เวชศาสตร์ฉุกเฉิน",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 31,
    groupname: "แพทย์พยาธิวิทยากายวิภาค",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 32,
    groupname: "สวัสดิการสังคม",
    active: "Y",
    edituserid: 2,
    userlogid: 2,
  },
  {
    id: 33,
    groupname: "รังสี",
    active: "Y",
    edituserid: 2,
    userlogid: 2,
  },
  {
    id: 34,
    groupname: "ห้องรับเงิน",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 35,
    groupname: "Ward_ศัลยกรรมชาย",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 36,
    groupname: "เวชสถิติ",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 37,
    groupname: "สำนักงานด่านหน้า",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 38,
    groupname: "ศูนย์ ( CFO)",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 39,
    groupname: "ฝ่ายบัญชี",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 40,
    groupname: "เภสัชกร",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 41,
    groupname: "สำนักงานอายุรกรรม",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 42,
    groupname: "สำนักงานศัลยกรรม",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 43,
    groupname: "สำนักงานสูติกรรม",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 44,
    groupname: "สำนักงานศัลยกรรมกระดูก",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 46,
    groupname: "สำนักงานกุมารเวชกรรม",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 50,
    groupname: "หน่วยเฝ้าระวังการติดเชื้อ(NI)",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 51,
    groupname: "สุขศึกษา",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 52,
    groupname: "สำนักงานนิติเวช",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 53,
    groupname: "กลุ่มการพยาบาล",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 54,
    groupname: "เวชกรรมสังคม",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 55,
    groupname: "หัวใจและปอดเทียม",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 56,
    groupname: "พยาบาลหน่วยตรวจพิเศษ",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 57,
    groupname: "คลังเลือด",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 58,
    groupname: "Lab_Culture",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 59,
    groupname: "กลุ่มงานนโยบายและแผน",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 60,
    groupname: "โรงพยาบาลเมือง",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 61,
    groupname: "ศูนย์เวชจริยศาสตร์",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 62,
    groupname: "กลุ่มงานการพยาบาลชุมชน",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 63,
    groupname: "สำนักงานศูนย์โรคหัวใจ",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 64,
    groupname: "จนท.ห้องตรวจสุขภาพ",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 65,
    groupname: "จนท.ห้องตรวจ ARI, COVID, Labour",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 69,
    groupname: "จนท.ห้องตรวจอุบัติเหตุฉุกเฉิน",
    active: "Y",
    edituserid: 936,
    userlogid: 936,
  },
  {
    id: 88,
    groupname: "power_user",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 90,
    groupname: "จนท.ศูนย์แพทย์ศาสตร์",
    active: "Y",
    edituserid: 936,
    userlogid: 936,
  },
  {
    id: 94,
    groupname: "นิสิตแพทย์",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 95,
    groupname: "แพทย์แผนไทย",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 96,
    groupname: "แพทย์ Intern/ แพทย์ใช้ทุน",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 97,
    groupname: "แพทย์ Extern",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 98,
    groupname: "องค์กรแพทย์",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 99,
    groupname: "admin",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 100,
    groupname: "lab_exclusive",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 101,
    groupname: "viewhx",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 102,
    groupname: "POCT",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 103,
    groupname: "Lab_Genomic",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 110,
    groupname: "ทันตสาธารณสุข",
    active: "Y",
    edituserid: 936,
    userlogid: 936,
  },
  {
    id: 120,
    groupname: "พยาบาลห้องผ่าตัดหัวใจ",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 121,
    groupname: "Ward_ศัลยกรรมฉุกเฉิน (ESU)",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 122,
    groupname: "Ward_ศัลยกรรมทางเดินปัสสาวะและเด็ก",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 123,
    groupname: "Ward_ศัลยกรรมหญิง",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 124,
    groupname: "อาชีวเวชกรรม",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 125,
    groupname: "จนท.OPD ศูนย์โรคหัวใจ",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 126,
    groupname: "พยาบาลศูนย์โรคหัวใจ",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 127,
    groupname: "งานบริหารลูกหนี้",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 128,
    groupname: "งานประกันสุขภาพ",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 129,
    groupname: "ScanOPDCard",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 130,
    groupname: "IT start",
    active: "Y",
    edituserid: 2,
    userlogid: 2,
  },
  {
    id: 131,
    groupname: "TB",
    active: "Y",
    edituserid: 2,
    userlogid: 2,
  },
  {
    id: 132,
    groupname: "CT/MRI outsource",
    active: "Y",
    edituserid: 2,
    userlogid: 2,
  },
  {
    id: 133,
    groupname: "for COVID doctor",
    active: "Y",
    edituserid: 2,
    userlogid: 2,
  },
  {
    id: 134,
    groupname: "เวชระเบียน Online",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 135,
    groupname: "COVID-report",
    active: "Y",
    edituserid: 2,
    userlogid: 2,
  },
  {
    id: 136,
    groupname: "Field Hospital",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 137,
    groupname: "MDT team",
    active: "Y",
    edituserid: 2,
    userlogid: 2,
  },
  {
    id: 138,
    groupname: "นิสิตแพทย์-อายุรกรรม",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 139,
    groupname: "นิสิตแพทย์-ศัลยกรรม",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 140,
    groupname: "นิสิตแพทย์-สูติกรรม",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 141,
    groupname: "นิสิตแพทย์-กุมารเวชกรรม",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 142,
    groupname: "นิสิตแพทย์-รวมแผนก",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 143,
    groupname: "นิสิตแพทย์-ศัลยกรรมกระดูก",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 144,
    groupname: "นิสิตแพทย์-จักษุ",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 145,
    groupname: "นิสิตแพทย์-โสต ศอ นาสิก",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 146,
    groupname: "นิสิตแพทย์-จิตเวช",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 147,
    groupname: "นิสิตแพทย์-อุบัตเหตุฉุกเฉิน",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 148,
    groupname: "นิสิตแพทย์-เวชกรรมฟื้นฟู",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 149,
    groupname: "นิสิตแพทย์-นิติเวช",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 150,
    groupname: "SMC_Manager",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 160,
    groupname: "เวชกรรมฟื้นฟู",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 170,
    groupname: "กลุ่มจัดเวรOPD",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 171,
    groupname: "กลุ่มจัดเวรIPD",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 172,
    groupname: "กลุ่มจัดเวรสำนักงาน",
    active: "Y",
    edituserid: 12,
    userlogid: 12,
  },
  {
    id: 175,
    groupname: "OPD_ScreenHx",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 200,
    groupname: "OPD_แผนกอายุรกรรม ชั้น 2",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 202,
    groupname: "OPD_แผนกอายุรกรรม ชั้น 3",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 230,
    groupname: "OPD_แผนกศัลยกรรม",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 240,
    groupname: "OPD_แผนกสูตินรีเวช",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 250,
    groupname: "OPD_แผนกกุมารเวชกรรม",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 260,
    groupname: "OPD_แผนกENT",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 270,
    groupname: "OPD_แผนกจักษุ",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 280,
    groupname: "OPD_แผนกศัลยกรรมกระดูก",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 290,
    groupname: "OPD_แผนกจิตเวช",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 300,
    groupname: "OPD_ห้องตรวจไตเทียม",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 305,
    groupname: "OPD แพทย์แผนไทย",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 350,
    groupname: "OPD_แผนกอายุรกรรม ตึกมะเร็ง",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 355,
    groupname: "OPD คลินิกทวารเทียม",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 360,
    groupname: "OPD_เวชศาสตร์นิวเคลียร์",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 370,
    groupname: "OPD_รังสีรักษา",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 371,
    groupname: "รังสีรักษา-ลงข้อมูล",
    active: "Y",
    edituserid: 2,
    userlogid: 2,
  },
  {
    id: 380,
    groupname: "OPD_รังสีร่วมรักษา",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 395,
    groupname: "OPD เคมีบำบัด",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 400,
    groupname: "ศูนย์เครื่องช่วยหายใจ",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 590,
    groupname: "Ward_กระดูกหญิงและเด็ก",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 593,
    groupname: "Ward_ศัลยกรรมกระดูกชาย",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 600,
    groupname: "Ward_อายุรกรรมชาย 1",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 603,
    groupname: "Ward_อายุรกรรมชาย 2",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 606,
    groupname: "Ward_อายุรกรรมหญิง 1",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 609,
    groupname: "Ward_อายุรกรรมหญิง 2",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 612,
    groupname: "Ward_วิกฤตอายุรกรรม(MICU3)(IM1เดิม)",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 615,
    groupname: "Ward_วิกฤตอายุรกรรม(MICU4)(IM2เดิม)",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 620,
    groupname: "Ward_วิกฤตอายุรกรรม(MICU1)",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 623,
    groupname: "Ward_วิกฤตอายุรกรรม(MICU2)",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 626,
    groupname: "Ward_วิกฤตโรคหัวใจ",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 630,
    groupname: "Ward_โรคหลอดเลือดสมอง (Stroke Unit)",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 633,
    groupname: "Ward_จิตการุณ ชั้น 4 (พิเศษ)",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 636,
    groupname: "Ward_จิตการุณ ชั้น 5 (พิเศษ)",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 639,
    groupname: "Ward_จิตการุณ ชั้น 6",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 650,
    groupname: "Ward_มะเร็ง ชั้น6",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 653,
    groupname: "Ward_พิเศษอายุรกรรม ชั้น 7",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 656,
    groupname: "Ward_อายุรกรรม ชั้น 5 (พิเศษ)",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 657,
    groupname: "Ward_พิเศษอายุรกรรม ชั้น 9",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 659,
    groupname: "Ward_อายุรกรรม ชั้น7",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 662,
    groupname: "Ward_ตึกสงฆ์อาพาธ",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 665,
    groupname: "Ward_พิเศษสงฆ์อาพาธ",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 668,
    groupname: "Ward_ชีวาภิบาล",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 670,
    groupname: "Ward_ตึกให้ยาเคมีบำบัด",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 673,
    groupname: "Ward_สังเกตอาการผู้ป่วยตรวจสวนหัวใจ",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 700,
    groupname: "Ward_วิกฤตศัลยกรรม (SICU)",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 703,
    groupname: "Ward_ศัลยกรรมประสาทและศัลยกรรมตกแต่ง",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 706,
    groupname: "Ward_วิกฤตศัลยกรรมประสาท (NSICU)",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 709,
    groupname: "Ward_ศัลยกรรมอุบัติเหตุ",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 712,
    groupname: "Ward_วิกฤตอุบัติเหตุ (TICU)",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 720,
    groupname: "Ward_วิกฤตศัลยกรรมหัวใจและทรวงอก (ICU CVT)",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 723,
    groupname: "Ward_วิกฤตศัลยกรรมฉุกเฉิน(AICU)",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 730,
    groupname: "Ward_เทพรัตน์ 2",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 750,
    groupname: "Ward_สูติกรรม 1",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 753,
    groupname: "Ward_สูติกรรม 2",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 756,
    groupname: "Ward_สูติกรรม 3",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 759,
    groupname: "Ward_สูติกรรม 4",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 762,
    groupname: "Ward_สูติกรรม4(พิเศษรวม)",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 765,
    groupname: "Ward_สูติกรรมพิเศษ",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 770,
    groupname: "Ward_ตึกคลอด",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 780,
    groupname: "Ward_กุมารเวชกรรม",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 783,
    groupname: "Ward_ทารกแรกเกิด",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 786,
    groupname: "Ward_วิกฤตกุมารเวชกรรม(PICU)",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 789,
    groupname: "Ward_วิกฤตทารกแรกเกิด(NICU)",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 800,
    groupname: "Ward_จิตเวช",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 810,
    groupname: "Ward_จักษุ-โสต-ศอ-นาสิก",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 820,
    groupname: "Ward_แพทย์แผนไทย",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 900,
    groupname: "Ward_พิเศษรวมใจภักดิ์ 2",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 905,
    groupname: "Ward_พิเศษรวมใจภักดิ์ 3",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 910,
    groupname: "Ward_พิเศษรวมใจภักดิ์ 4",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 915,
    groupname: "Ward_พิเศษรวมใจภักดิ์ 5",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 1000,
    groupname: "Ward_สูติกรรม 2 (Cohort)",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 1003,
    groupname: "Ward_สูติกรรม 3 (Cohort)",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 1006,
    groupname: "Ward_สูติกรรม 4 (Cohort)",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 2000,
    groupname: "นักวิทยาศาสตร์การแพทย์พยาธิวิทยากายวิภาค",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 2001,
    groupname: "จนท.พยาธิวิทยากายวิภาค",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 2041,
    groupname: "เภสัชกรรมบริบาลผู้ป่วยใน",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 2050,
    groupname: "งานประกันชีวิต",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 2055,
    groupname: "จัดเก็บผู้ป่วยนอก",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 2100,
    groupname: "จนท.OR ศูนย์โรคหัวใจ",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 2110,
    groupname: "จนท.ห้องผ่าตัด",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 2111,
    groupname: "พยาบาลห้องผ่าตัด",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 2121,
    groupname: "พยาบาลวิสัญญี",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 2150,
    groupname: "ห้องตรวจ OSCC [นิติเวช]",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 2151,
    groupname: "งานเก็บรักษาศพ [นิติเวช]",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 2160,
    groupname: "ศูนย์เปล",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 2161,
    groupname: "ศูนย์เปล OPD",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 2170,
    groupname: "นักโภชนาการ",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
  {
    id: 2200,
    groupname: "ห้องจ่ายยาแพทย์ทางเลือก",
    active: "Y",
    edituserid: 307,
    userlogid: 307,
  },
];

async function seed() {
  await AppGroup.bulkCreate(groups);
  console.log("AppGroup seeding completed.");
}

seed();
