const AppPerson = require("../models/app_person"); // model ที่ import มา

async function seed() {
  await AppPerson.bulkCreate([
    {
      id: 3962,
      PSCodeID: null,
      pscode: "172858",
      salutation: 3,
      firstname: "เเพทย์",
      lastname: "หนึ่ง",
      GroID: null,
      OffID: 1,
      PosID: 60104,
      NursePosID: null,
      Poslevel: "ชำนาญการ",
      Sex: "หญิง",
      DivID: null,
      DepartID: 18,
      SsjID: null,
      WorkPoint: null,
      Specialty: null,
      Gradlevel: 4,
      Graduate: null,
      Educate: "0",
      Birthday: "1987-10-18",
      StartJobdate: "2012-04-10",
      ExpertID: 99999,
      EndJobdate: "0000-00-00",
      AcademicGroup: null,
      Remark: null,
      Active: null,
      FuncUnitID: 30,
      StatusID: 1,
      Up_date: null,
      TypeMID: 2,
      TypePayMid: 2,
      TypeDC: null,
      Inscl: null,
      CITIZEN: "5543679854613",
      NOBANK: null,
      TAXID: null,
      salary: "16460.00",
      EndUser: 2829,
      KeyDate: "2025-01-31",
      Unions: null,
      StatusMember: null,
      picperson: null,
      NurseCrNo: null,
      Engprename: "Miss",
      Engname: "phat",
      Engsurname: "nueng",
      Email: "phat_22@hotmail.com",
      Fiveyear: null,
      Username: null,
      Password: null,
      UserKey: null,
      CodeCSMBS: null,
      FiveyearNurse: null,
      NolicensedClinic: "43246",
      HN: 6842151,
      Director: "N",
      PosLevelOLD: null,
      BloodGroup: null,
      SendDev: "N",
      HomePhone: "",
      MobilePhone: "",
      JobEducate: null,
      IP: "172.16.1.254",
    },
  ]);

  console.log("✅ app person seeded with 10 sample records");
}

seed();
