const DoctorFlag = require("../models/doctor_flag");

const doctor_flag = [
  {
    tablename: "doctor_name",
    columnname: "doctordepart",
    columnvalue: "100",
    descvalue: "อายุรกรรม",
    note: "100",
  },
  {
    tablename: "doctor_name",
    columnname: "doctordepart",
    columnvalue: "200",
    descvalue: "ศัลยกรรม",
    note: "200",
  },
  {
    tablename: "doctor_name",
    columnname: "doctordepart",
    columnvalue: "300",
    descvalue: "กุมารเวชกรรม",
    note: "500",
  },
  {
    tablename: "doctor_name",
    columnname: "doctordepart",
    columnvalue: "400",
    descvalue: "สูตินรีเวชกรรม",
    note: "300, 400",
  },
  {
    tablename: "doctor_name",
    columnname: "doctordepart",
    columnvalue: "500",
    descvalue: "ศัลยกรรมออโธปิดิกส์",
    note: "800",
  },
  {
    tablename: "doctor_name",
    columnname: "doctordepart",
    columnvalue: "510",
    descvalue: "โสตศอนาสิก",
    note: "600",
  },
  {
    tablename: "doctor_name",
    columnname: "doctordepart",
    columnvalue: "520",
    descvalue: "จักษุวิทยา",
    note: "700",
  },
  {
    tablename: "doctor_name",
    columnname: "doctordepart",
    columnvalue: "530",
    descvalue: "วิสัญญีวิทยา",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctordepart",
    columnvalue: "540",
    descvalue: "จิตเวช",
    note: "900",
  },
  {
    tablename: "doctor_name",
    columnname: "doctordepart",
    columnvalue: "550",
    descvalue: "พยาธิวิทยากายวิภาค",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctordepart",
    columnvalue: "555",
    descvalue: "นิติเวชวิทยา",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctordepart",
    columnvalue: "560",
    descvalue: "เวชศาสตร์ฉุกเฉิน",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctordepart",
    columnvalue: "570",
    descvalue: "เวชศาสตร์ครอบครัว",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctordepart",
    columnvalue: "580",
    descvalue: "เวชกรรมฟื้นฟู",
    note: "120",
  },
  {
    tablename: "doctor_name",
    columnname: "doctordepart",
    columnvalue: "590",
    descvalue: "เวชกรรมสังคม",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctordepart",
    columnvalue: "600",
    descvalue: "ทันตกรรม",
    note: "110",
  },
  {
    tablename: "doctor_name",
    columnname: "doctordepart",
    columnvalue: "610",
    descvalue: "รังสีวิทยา",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctordepart",
    columnvalue: "620",
    descvalue: "แพทย์ทางเลือก",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctordepart",
    columnvalue: "900",
    descvalue: "ผู้ป่วยนอก",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorlevel",
    columnvalue: "A",
    descvalue: "นิสิตแพทย์",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorlevel",
    columnvalue: "B",
    descvalue: "Extern",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorlevel",
    columnvalue: "C",
    descvalue: "Intern/ แพทย์ใช้ทุน",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorlevel",
    columnvalue: "D",
    descvalue: "Resident",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorlevel",
    columnvalue: "E",
    descvalue: "Staff",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "A10",
    descvalue: "อายุรศาสตร์ทั่วไป",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "A11",
    descvalue: "อายุรศาสตร์โรคไต",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "A12",
    descvalue: "อายุรศาสตร์โรคหัวใจ",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "A13",
    descvalue: "อายุรศาสตร์ประสาทวิทยา",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "A14",
    descvalue: "อายุรศาสตร์เวชบำบัดวิกฤต",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "A15",
    descvalue: "อายุรศาสตร์โรคต่อมไร้ท่อ",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "A16",
    descvalue: "อายุรศาสตร์มะเร็งวิทยา",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "A17",
    descvalue: "อายุรศาสตร์โรคระบบการหายใจ และภาวะวิกฤตโรคระบบการหายใจ",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "A18",
    descvalue: "อายุรศาสตร์โรคเลือด",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "A19",
    descvalue: "อายุรศาสตร์โรคติดเชื้อ",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "A20",
    descvalue: "อายุรศาสตร์ตจวิทยา",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "A21",
    descvalue: "อายุรศาสตร์ระบบทางเดินอาหาร",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "A22",
    descvalue: "อายุรศาสตร์โรคข้อและรูมาติสม",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "A23",
    descvalue: "อายุรศาสตร์ทั่วไปสาขาโภชนบำบัด",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "B10",
    descvalue: "ศัลยศาสตร์ทั่วไป",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "B11",
    descvalue: "ศัลยศาสตร์ยูโรวิทยา",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "B12",
    descvalue: "ศัลยศาสตร์ทรวงอก",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "B13",
    descvalue: "ศัลยศาสตร์ตกแต่ง",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "B14",
    descvalue: "ศัลยศาสตร์ระบบประสาท",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "B15",
    descvalue: "กุมารศัลยศาสตร์",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "C10",
    descvalue: "กุมารเวชศาสตร์ทั่วไป",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "C11",
    descvalue: "กุมารเวชศาสตร์โรคหัวใจ",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "C12",
    descvalue: "กุมารเวชศาสตร์โรคเลือด",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "C13",
    descvalue: "กุมารเวชศาสตร์โรคไต",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "C14",
    descvalue: "กุมารเวชศาสตร์โรคระบบทางเดินหายใจ",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "C15",
    descvalue: "กุมารเวชศาสตร์โรคต่อมไร้ท่อและเมตาบอลิสม",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "C16",
    descvalue: "กุมารเวชศาสตร์ทารกแรกเกิดและปริกำเนิด",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "C17",
    descvalue: "กุมารเวชศาสตร์โรคระบบประสาท",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "D10",
    descvalue: "สูติศาสตร์-นรีเวชวิทยา",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "E10",
    descvalue: "ศัลยศาสตร์ออโธปิดิกส์",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "F10",
    descvalue: "โสต นาสิก ลาริงซ์วิทยา",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "G10",
    descvalue: "จักษุวิทยา",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "H10",
    descvalue: "วิสัญญีวิทยา",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "I10",
    descvalue: "จิตเวชศาสตร์",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "I11",
    descvalue: "จิตเวชเด็กและวัยรุ่น",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "J10",
    descvalue: "พยาธิวิทยากายวิภาค",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "K10",
    descvalue: "นิติเวชศาสตร์",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "L10",
    descvalue: "ทันตกรรม",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "M10",
    descvalue: "เวชปฏิบัติทั่วไป(GP)",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "N10",
    descvalue: "เวชศาสตร์ครอบครัว",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "O10",
    descvalue: "เวชศาสตร์ครอบครัวและเวชศาสตร์ป้องกันสาขาสุขภาพจิตชุมชน",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "P10",
    descvalue: "เวชศาสตร์ป้องกัน(ระบาดวิทยา)",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "Q10",
    descvalue: "เวชศาสตร์ฟื้นฟู",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "R10",
    descvalue: "รังสีวิทยาทั่วไป",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "R11",
    descvalue: "รังสีวิทยาวินิจฉัย",
    note: null,
  },
  {
    tablename: "doctor_name",
    columnname: "doctorspecialist",
    columnvalue: "S10",
    descvalue: "เวชศาสตร์ฉุกเฉิน",
    note: null,
  },
];

async function seed() {
  await DoctorFlag.bulkCreate(doctor_flag);
  console.log("Doctor flag seeders success");
}

seed();
